@server_url = http://localhost:5166

### Login student
POST {{server_url}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "student@test.com",
  "password": "{{password}}"
}

> {%
  client.global.set("token", response.body.accessToken);
%}

### Login teacher
POST {{server_url}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "teacher@test.com",
  "password": "{{password}}"
}

> {%
    client.global.set("token", response.body.accessToken);
%}

### Get all activities
GET {{server_url}}/api/activities
Accept: application/json
Authorization: Bearer {{token}}

### Create new activity
POST {{server_url}}/api/activities
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "New Activity",
  "description": "This is a new activity created via HTTP request.",
  "startDate": "2024-07-01T09:00:00Z",
  "endDate": "2024-07-01T17:00:00Z",
  "type": {"name": "Examination"},
  "moduleId": "e04e457e-8cdd-4af6-ae15-a77f52dff46c"
}

### Get paged users
GET {{server_url}}/api/users?page=2&pageSize=10
Accept: application/json
Authorization: Bearer {{token}}


### Get paged activities
GET {{server_url}}/api/activities?page=1&pageSize=10
Accept: application/json
Authorization: Bearer {{token}}

### Get paged courses
GET {{server_url}}/api/courses?page=1&pageSize=10
Accept: application/json
Authorization: Bearer {{token}}

### create course
POST {{server_url}}/api/courses
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{"name":"asd",
  "description":"asd",
  "startDate":"2026-03-01",
  "endDate":"2026-04-30",
  "modules":[
    {
      "name":"asd",
      "description":"asd",
      "startDate":"2026-04-01",
      "endDate":"2026-04-03",
      "courseId":"564dff0b-e4e5-42c3-ac92-0cb0dfc4bd18"},
    {
      "name":"dsa","description":"dsa",
      "startDate":"2026-03-29",
      "endDate":"2026-04-30",
      "courseId":"564dff0b-e4e5-42c3-ac92-0cb0dfc4bd18"}
  ]
}
